name: Joplin Continuous Integration
on: [push, pull_request]
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2.1
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Run script...
        run: |
          "${GITHUB_WORKSPACE}/.github/scripts/run_ci.sh"
